version: '3.1'
services:
  
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: trabalho_final
      MYSQL_USER: samuelSQL
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3304:3306
    expose:
      - '3306'
    networks:
      - mysql_api

  api:
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: meu-mysql
    ports:
      - 3000:3000
    depends_on:
      - db 
    networks:
      - mysql_api
    command: sh -c 'until nc -z db 3306; do sleep 1; done; sleep 5 && npx nodemon app.js'

networks:
  mysql_api:
